services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: mamboota/devops-for-developers-project-74:latest
    command: make test
    environment:
      - NODE_ENV=production